version: "3"
services:
  test:
    build: .
    ports:
      - "3100"
    container_name: gfw-geostore-api-test
    environment:
      NODE_ENV: test
      CARTODB_USER: test
      NODE_PATH: app/src
      GATEWAY_URL: http://mymachine:9000
      API_VERSION: v1
      STAMPERY_TOKEN: token
      MONGO_PORT_27017_TCP_ADDR: mongo
      MICROSERVICE_TOKEN: cttoken
      LOCAL_URL: http://geostore.default.svc.cluster.local:3100
      FASTLY_ENABLED: "false"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
    command: test
    depends_on:
      - mongo

  mongo:
    image: mongo:3.4
    command: --smallfiles
    ports:
      - "27017"
