version: "3"
services:
  develop:
    build: .
    ports:
      - "3100:3100"
    container_name: gfw-geostore-api-develop
    env_file:
      - dev.env
    environment:
      PORT: 3100
      NODE_ENV: dev
      NODE_PATH: app/src
      API_VERSION: v1
      MONGO_PORT_27017_TCP_ADDR: mongo
      FASTLY_ENABLED: "false"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
    command: develop
    depends_on:
      - mongo
    volumes:
      - ./app:/opt/gfw-geostore-api/app
  mongo:
    image: mongo:3.4
    container_name: gfw-geostore-mon
    command: --smallfiles
    ports:
      - "27017"
    volumes:
      - $HOME/docker/data/gfw-geostore-api:/data/db
    restart: always
